name: hackslash

dependencies:
 - base
 - binary
 - binary-strict
 - bytestring
 - dependent-sum
 - filepath
 - foreign-store
 - linear
 - mtl
 - random
 - rapid
 - reflex
 - reflex-sdl2
 - sdl2
 - stm
 - text
 - unordered-containers
 - vector

c-sources:
  - cbits/freeablo.cpp

include-dirs:
  include
  freeablo/components
  freeablo/apps/freeablo

extra-lib-dirs:
  freeablo/apps/freeablo
  freeablo/extern/StormLib

extra-libraries:
  freeablo_lib
  RocketCore
  GL
  SDL2
  png
  SDL2_image
  SDL2_mixer
  Storm
  boost_serialization
  boost_python
  boost_system
  boost_filesystem
  enet
  python2.7
  stdc++

executables:
  hackslash:
    main: Main.hs
    source-dirs:
      - src
