name: hackslash

dependencies:
 - astar
 - base
 - foreign-store
 - hashable
 - linear
 - mtl
 - rapid
 - reflex
 - reflex-sdl2
 - sdl2
 - unordered-containers

c-sources:
  - cbits/freeablo.cpp

include-dirs:
  include
  freeablo/components
  freeablo/apps/freeablo

extra-lib-dirs:
  freeablo/apps/freeablo
  freeablo/extern/StormLib

extra-libraries:
  freeablo_lib
  RocketCore
  GL
  SDL2
  png
  SDL2_image
  SDL2_mixer
  Storm
  boost_serialization
  boost_python
  boost_system
  boost_filesystem
  enet
  python2.7
  stdc++

executables:
  hackslash:
    main: Main.hs
    source-dirs:
      - src
