name: yamplo

dependencies:
 - base
 - binary
 - binary-strict
 - bytestring
 - filepath
 - foreign-store
 - linear
 - random
 - rapid
 - sdl2
 - stm
 - text
 - unordered-containers
 - vector
 - Yampa

executables:
  yamplo:
    main: Main.hs
    source-dirs:
      - src
