name: hackslash

dependencies:
 - base
 - binary
 - binary-strict
 - bytestring
 - dependent-sum
 - filepath
 - foreign-store
 - linear
 - mtl
 - random
 - rapid
 - reflex
 - reflex-sdl2
 - sdl2
 - stm
 - text
 - unordered-containers
 - vector

executables:
  hackslash:
    main: Main.hs
    source-dirs:
      - src
