resolver: lts-9.11

packages:
- '.'

- location:
    git: https://github.com/reflex-frp/reflex
    commit: 36db894180d015fdd032d7d3a338e0b5ac9df4b4
  extra-dep: true

- location:
    git: https://github.com/dalaing/reflex-sdl2
    commit: d85ab65605b3d2a90f4380c5f883335953b299e4
  extra-dep: true

extra-deps:
- astar-0.3.0.0
- rapid-0.1.3
- prim-uniq-0.1.0.1
- ref-tf-0.4.0.1

ghc-options:
  hackslash: "-fPIC -fobject-code"
