resolver: nightly-2016-06-15

packages:
- '.'

- location: /home/bart/sources/sdl2
    #git: https://github.com/haskell-game/sdl2
    #commit: 472f3abe8a9a1e8970b19e9f91a65f6c62a8a97d
  extra-dep: true

- location:
    git: git@github.com:ivanperez-keera/Yampa.git
    commit: 68e149c5b668b61e73c87725492879416c3aad7f
  extra-dep: true

extra-deps:
- binary-strict-0.4.8.3

rebuild-ghc-options: true
ghc-options:
    yamplo: "-threaded -O2 -rtsopts -with-rtsopts=-N -Wall -lSDL2_image -lSDL2_mixer"
