resolver: nightly-2016-09-17

packages:
- '.'

- location: /home/bart/sources/sdl2
    # git: https://github.com/haskell-game/sdl2
    # commit: e0812f7285ce33842fa9bccd9ea04d66590e8090
  extra-dep: true

- location:
    git: https://github.com/reflex-frp/reflex
    commit: a63aba90bdea5ae5b3e1506d468613bdfedcdfa3
  extra-dep: true

- location:
    git: https://github.com/dalaing/reflex-sdl2
    commit: a98f0f154c2159f5170b0c280d09762f2b6b2a2a
  extra-dep: true

extra-deps:
- binary-strict-0.4.8.3
- exception-transformers-0.4.0.4
- haskell-src-exts-1.17.1
- haskell-src-meta-0.6.0.14
- rapid-0.1.2
- ref-tf-0.4.0.1

ghc-options:
  hackslash: "-fPIC -fobject-code"
