resolver: lts-7.9

packages:
- '.'

- location:
    git: https://github.com/haskell-game/sdl2
    commit: e0812f7285ce33842fa9bccd9ea04d66590e8090
  extra-dep: true

- location:
    git: https://github.com/reflex-frp/reflex
    commit: 91299fce0bb2caddfba35af6608df57dd31e3690
  extra-dep: true

- location:
    git: https://github.com/dalaing/reflex-sdl2
    commit: 152179bfddcec53b3764ba460101d292af4e0304
  extra-dep: true

extra-deps:
- astar-0.3.0.0
- rapid-0.1.2
- prim-uniq-0.1.0.1
- ref-tf-0.4.0.1
- MemoTrie-0.6.7
- newtype-generics-0.5

ghc-options:
  hackslash: "-fPIC -fobject-code"
