packages:
- '.'

- location: /home/bart/sources/sdl2
    #git: https://github.com/haskell-game/sdl2
    #commit: 472f3abe8a9a1e8970b19e9f91a65f6c62a8a97d
  extra-dep: true

extra-deps:
- binary-strict-0.4.8.3

resolver: lts-3.13

rebuild-ghc-options: true
ghc-options:
    yamplo: "-threaded -O2 -rtsopts -with-rtsopts=-N -Wall -lSDL2_image -lSDL2_mixer"
