resolver: nightly-2016-06-15

packages:
- '.'

- location:
    git: https://github.com/haskell-game/sdl2
    commit: e0812f7285ce33842fa9bccd9ea04d66590e8090
  extra-dep: true

- location:
    git: git@github.com:ivanperez-keera/Yampa.git
    commit: 68e149c5b668b61e73c87725492879416c3aad7f
  extra-dep: true

- location: /home/bart/sources/rapid
  extra-dep: true

extra-deps:
- binary-strict-0.4.8.3

rebuild-ghc-options: true
ghc-options:
    yamplo: "-threaded -O2 -rtsopts -with-rtsopts=-N -Wall -lSDL2_image -lSDL2_mixer"
