resolver: nightly-2017-11-09

packages:
- '.'

- location:
    git: https://github.com/reflex-frp/reflex
    commit: 60d2878142943487987feeeea108dbed5405f469
  extra-dep: true

- location:
    git: https://github.com/schell/reflex-sdl2
    commit: b2089accef02ee218a8ec7d909471b34f824f09e
  extra-dep: true

extra-deps:
- astar-0.3.0.0
- rapid-0.1.3
- prim-uniq-0.1.0.1
- ref-tf-0.4.0.1

ghc-options:
  hackslash: "-fPIC -fobject-code"
